language: node_js
sudo: required
services:
    - docker

before_install:
    - docker build -t jackhwl/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jackhwl/docker-react npm run test
